#!/bin/sh



xrdb merge /home/chaman/.config/x11/Xresources
xset r rate 300 60 &
picom --backend glx --vsync --blur-background --shadow-ignore-shaped -f --config /home/chaman/.config/picom/picom.conf &

feh --bg-fill ~/.local/share/wall.png --no-fehbg &
/usr/lib/notification-daemon-1.0/notification-daemon &
/home/chaman/.local/bin/remap &
/home/chaman/.local/bin/battery_notify &
xidlehook --not-when-audio --not-when-fullscreen --timer 60 '/home/chaman/.local/bin/betterlockscreen -l blur -q' '' &

dash ~/.config/chadwm/scripts/bar.sh &
while type chadwm >/dev/null; do chadwm && continue || break; done
